services:
  gateway:
    container_name: gateway
    build:
      context: . 
      dockerfile: ./Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8086:8080"
    networks:
      - product_network
      - monitoring_network
      - user_network
      - order_network
  user_service:
    container_name: user_service
    build:
      context: . 
      dockerfile: ./UserService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=user_db;Port=5432;Database=${POSTGRES_USER_DB};Username=${POSTGRES_USER_USER};Password=${POSTGRES_USER_PASSWORD}
    ports:
      - "8081:8080"
    depends_on:
      user_db:
        condition: service_healthy
    networks:
      - user_network
  
  user_db:
    container_name: user_db
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER_USER}
      - POSTGRES_PASSWORD=${POSTGRES_USER_PASSWORD}
      - POSTGRES_DB=${POSTGRES_USER_DB}
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - user_network
    ports:
      - "5434:5432" #to development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 1s
      timeout: 5s
      retries: 10

  product_service:
    container_name: product_service
    build:
      context: . 
      dockerfile: ./ProductService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=product_db;Port=5432;Database=${POSTGRES_PRODUCT_DB};Username=${POSTGRES_PRODUCT_USER};Password=${POSTGRES_PRODUCT_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      product_db:
        condition: service_healthy
    networks:
      - product_network

  product_db:
    container_name: product_db
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_PRODUCT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PRODUCT_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PRODUCT_DB}
    volumes:
      - product_db_data:/var/lib/postgresql/data
    networks:
      - product_network
    ports:
      - "5433:5432" #to development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 1s
      timeout: 5s
      retries: 10

  order_service:
    container_name: order_service
    build:
      context: . 
      dockerfile: ./OrderService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=order_db;Port=5432;Database=${POSTGRES_ORDER_DB};Username=${POSTGRES_ORDER_USER};Password=${POSTGRES_ORDER_PASSWORD}
    ports:
      - "8083:8080"
    depends_on:
      order_db:
        condition: service_healthy
    networks:
      - order_network

  order_db:
    container_name: order_db
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_ORDER_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ORDER_PASSWORD}
      - POSTGRES_DB=${POSTGRES_ORDER_DB}
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - order_network
    ports:
      - "5435:5432" #to development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 1s
      timeout: 5s
      retries: 10
  
  prometheus:
    image: prom/prometheus:v3.8.0
    volumes:
      - ./infra/prometheus:/etc/prometheus/
      - prometheus_data:/prometheus/
    container_name: prometheus-microservices
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - monitoring_network
      - product_network
  
  grafana:
    image: grafana/grafana:12.4.0-20447603318
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - DS_PROMETHEUS=someuid123
      - PROMETHEUS_URL=http://prometheus-microservices:9090
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/dashboards:/var/lib/grafana/dashboards
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    container_name: grafana-microservices
    networks:
      - monitoring_network
  
  vector:
    image: timberio/vector:0.52.0-alpine
    container_name: vector
    depends_on:
      - product_service
    volumes:
      - ./infra/vector.yaml:/etc/vector/vector.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - product_network
      - monitoring_network
  
  loki:
    hostname: loki
    container_name: loki
    image: grafana/loki:latest
    environment:
      TZ: ${SYSTEM_TIMEZONE:-Europe/Moscow}
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring_network
  
volumes:
  product_db_data:
  order_db_data:
  grafana_data:
  prometheus_data:
  user_db_data:

networks:
  product_network:
  monitoring_network:
  user_network:
  order_network:
